version: '3.7'

services:
  nginx:
    image: matthew-hallsworth:symfony-nginx
    build:
      context: ./docker/dev/nginx
    volumes:
      - .:/var/www/html:rw,cached
    ports:
      - 80:80
      - 443:443
  fpm:
    image: matthew-hallsworth:symfony-fpm
    build:
      context: ./docker/dev/fpm
    volumes:
      - .:/var/www/html:rw,cached
  mysql:
    image: matthew-hallsworth:symfony-mysql
    build:
      context: ./docker/dev/mysql
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
  memcached:
    image: matthew-hallsworth:symfony-memcached
    image: memcached:latest
    ports:
      - 11211:11211
    command: ["-m", "1024m"]
